# Uncomment the next line to define a global platform for your project
platform :ios, '12.1'

target 'ExistingIOSProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ExistingIOSProject

  flutter_application_path = '../my_flutter/'
  eval(File.read(
       File.join(flutter_application_path,
                 '.ios', 'Flutter', 'podhelper.rb')),
       binding)
end
